# Generated by Django 5.2 on 2025-04-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_education_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='about',
            field=models.TextField(default='About me'),
        ),
    ]
